version: '2'
catalog:
  name: "Labsgui"
  version: "v1.0"
  description: "Labs GUI"
  uuid: labsgui-1
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "RESTART"
      lable: "Always Restart"
      description: "Docker Always Restart"
      default: false
      type: "boolean"

    - variable: "OWNDNS"
      lable: "DNS and Search activate?"
      description: "Own DNS and Search Domain?"
      default: true
      type: "boolean"

    - variable: "GUIIMAGE"
      label: "GUI Image"
      description: "Select some Image"
      options:
        - icd-gui
      required: true
      default: "icd-gui"
      type: "enum"

    - variable: "DNS_SERVER"
      label: "DNS Server"
      description: "Your DNS Server"
      required: false
      default: "192.168.0.1"
      type: "string"

    - variable: "DNS_SEARCH"
      label: "DNS Search Domain"
      description: "Your DNS Search Domain"
      required: false
      default: "icd-gmbh.de"
      type: "string"

    - variable: "PORT1578"
      label: "Port 1578 (boxcli)"
      description: "Port 1578"
      required: true
      default: "1578"
      type: "int"

    - variable: "PORT1581"
      label: "Port 1581 (guisrv)"
      description: "Port 1581"
      required: true
      default: "1581"
      type: "int"

    - variable: "PORT8080"
      label: "Port 8080 (tomcat)"
      description: "Port 8080"
      required: false
      default: ""
      type: "int"

labsgui:
