version: '2'
catalog:
  name: "Labsgui"
  version: "v1.0"
  description: "Labs GUI"
  uuid: labsgui-1
  minimum_rancher_version: v1.2.0
  questions:

    - variable: "GUIIMAGE"
      label: "GUI Image"
      description: "Select some Image"
      options:
        - icd-gui
        - icd-gui-NoTomcatGui
      required: true
      default: "icd-gui"
      type: "enum"

    - variable: "LINKPATH"
      label: "Linked Path"
      description: "Host Path to /usr/local/gui"
      default: "/vm-partner1"
      required: true
      type: "string"

    - variable: "RESTART"
      lable: "Always Restart"
      description: "Docker Always Restart"
      default: true
      type: "boolean"

    - variable: "PORT1577"
      label: "Port 1577 (boxsrv)"
      description: "Port 1577"
      required: true
      default: "1577"
      type: "int"

    - variable: "PORT1581"
      label: "Port 1581 (guisrv)"
      description: "Port 1581"
      required: true
      default: "1581"
      type: "int"

    - variable: "PORT8080"
      label: "Port 8080 (tomcat)"
      description: "Port 8080"
      required: true
      default: "8080"
      type: "int"

labsdb:
